### ISSUE TITLE
Make direct indexing mode configurable over RPC

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#127]
Make it possible to change which contracts/accounts we restrict statediffing to over RPC when doing direct indexing

**Comment by ashwinphatak** [comment]
Notes from discussion:

* API to Add/Append, Remove/Delete, Set, Clear watched addresses
* New table in ipld-eth-db to store watched addresses and status
* Handling uniswap like scenarios where Pool has events in the same block where it got created:
  * Watcher calls ipld-eth-server with contract address + creation block hash, which proxies the call to vulcanize/geth
  * vulcanize/geth starts watching the contract at current block hash
  * ipld-eth-server kicks off / tracks till completion the statediffing (eth_writeStateDiff) for missed blocks from (creation till addition), calling upstream process (vulcanize/geth for now, but eth-statediff-service cluster in the future)

**Comment by prathamesh0** [comment]
Tasks:

vulcanize-geth:
- [x] An API to change watched addresses
- [x] Use a map for watched addresses and pre-compute their hashes
- [x] Tests

ipld-eth-db:
- [x] Migration for a table that stores watched addresses
- [x] Add column(s) to track watched address gap filling status
- [x] Move the watched addresses table to a different schema
- [ ] Update UML
- [x] Changes in pre- and post- migration sets
- [ ] https://github.com/vulcanize/ipld-eth-db/issues/42

ipld-eth-server:
- [x] An API that proxies the call to change watched addresses to geth
- [x] A service to fill indexing gap for watched addresses
- [x] Tests:
  - [x] API tests
  - [x] Service tests

**Comment by ashwinphatak** [comment]
Changes:

- [x] Remove slot based watching/params etc for current impl. Only watching of addresses will be supported. Implicitly, we watch all storage slots for an address.
- [x] Goal: Make getStorageAt work for watched contracts

**Comment by prathamesh0** [comment]
The service to fill indexing gap for watched addresses has been extracted to a separate repository.

**Comment by i-norden** [comment]
Tracking remaining tasks separately: https://github.com/vulcanize/ipld-eth-db/issues/81 https://github.com/vulcanize/ipld-eth-db/issues/42
