### ISSUE TITLE
Journal blocks that are pending statediffing when the node is shutdown

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#131]
We have a buffered channel between the chain events and the statediffing service, when we shutdown geth this channel should be flushed and the blocks inside it journaled so that we can generate their statediffs on node restart.

We don't necessarily need to flush the entire blocks to a journal, we could just journal the block heights or the lowest block height from which we need to pick up statediffing from.

Related, we need to make sure our containers are shutting down geth properly.

**Comment by ashwinphatak** [comment]
Can also be implemented as a process/continuous check in ipld-eth-server

Also see https://github.com/vulcanize/watcher-ts/issues/265

**Comment by i-norden** [comment]
This process should also mark where a shutdown gap begins in the table introduced here https://github.com/vulcanize/ipld-eth-db/issues/52

**Comment by abdulrabbani00** [comment]
@i-norden and @ashwinphatak - I believe this is no longer needed as the `known_gaps` table will populate missed gaps at start up. Therefore we don't need to keep track of blocks when `geth` shuts down.

**Comment by i-norden** [comment]
@telackey just pinging here for your visibility
