### ISSUE TITLE
CI test to make sure CLI flags still turn on the statediffing service after a rebase

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#181]
Usually the culprit for a break in the statediffing service configuration is due to changes in `cmd/geth/config.go.makeFullNode()`

**Comment by abdulrabbani00** [comment]
@i-norden - Would you be able to provide more context? This is the assumption that I am making:

* You want me to put together some sort of GitHub action workflow that will do the following:
  * Be triggered on a "rebase" event.
  * Run geth with a few preconfigured CLI flags.
  * Make sure that the statediffing service is running properly.
* Please let me know if these assumptions are accurate. If they are, can you help me understand the following?
  * In what context are you using "rebase?"
  * Are there a specified set of CLI flags used that you want me to test with?
  * The following [variable](https://github.com/vulcanize/go-ethereum/blob/statediff/core/blockchain.go#L135) should indicate whether statediff has started

Thank you

**Comment by abdulrabbani00** [comment]
@i-norden - This seems to be a low lift, just a few questions:

* When you say `rebase`, are you referring to fetching from upstream?
* Should we check for any differences in the `cmd/geth/config.go.makeFullNode()` function?

I would assume the CI Action would do the following:
1. Trigger on fetch from upstream.
2. Build`geth-linux-amd`
3. Start `geth-linux-amd` using the `--statediff` flags.
4. Ensure that geth runs with a 0 return code.
