### ISSUE TITLE
Epic: Proper truncating of levelDB; using our Postges DB as only historical archive

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#193]
and the ancient data/freezer

**Comment by i-norden** [comment]
Only maintain 128-256 blocks worth of data (block data + state) in an in-memory LevelDB. The rest of the (statediffed) data is written to Postgres, which serves as our only historical archive. When a node is shutdown or crashes, we can recover/rebuild the head state from Postgres. This mode of the client enables being able to begin syncing from some arbitrary state of the/a Postgres DB.

**Comment by i-norden** [comment]
I will link all the related child issues soon, there are a lot.

**Comment by AFDudley** [comment]
Thanks for this ticket, we need a new Epic and/or to change the name of the project.

**Comment by i-norden** [comment]
@i-norden I need to clean up the story here

**Comment by i-norden** [comment]
I believe this is fully encapsulated by the eth_probe work
