### ISSUE TITLE
(v5) Record headers from different node sources

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#196]
Replace the node_id field in the eth.header_cids table with a node_ids integer array field. When a unique node source inserts a duplicate header, they add their id to this array. This serves as a means to track the "breadth" of data as a measure of validity.

**Comment by abdulrabbani00** [comment]
@i-norden - After a bit of research, it seems like if we want to utilize an array for `eth.header_cids(node_id)` we will have to consider a workaround for the FK constraint to `public.nodes(node_id)`. A few preliminary options:

1. Drop the FK constraint to `public.nodes(node_id)`.
2. Use a junction table.
3. Perhaps some other solution I am unaware of. 

Also to keep in mind, I am only considering v3, not v4.

**Comment by i-norden** [comment]
Dropping is fine I think, since we can't have in-place FK constraints in timescaledb anyways. If/when we implement FK checks in some other capacity (e.g. trigger functions that "manually" check for records on INSERTs) it can be handled in that manner. (i.e. another solution for 3 would be a trigger function that checks for existence on inserts to `header_cids`, but we can implement this later).

**Comment by abdulrabbani00** [comment]
PR - Outdated!
- ipld-eth-db: https://github.com/vulcanize/ipld-eth-db/pull/90
- go-ethereum: https://github.com/vulcanize/go-ethereum/pull/239

**Comment by abdulrabbani00** [comment]
@i-norden - Can you review the above when you have a chance?
