### ISSUE TITLE
Option to process only some fraction of blocks at head

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#213]
E.g. every even block, only process diffs when `block_number % 2 == 0`.

In this manner, we can have multiple geth nodes processing statediffs at head in parallel without duplicating efforts. We can support some configurable degree of overlap/redundancy across multiple geth nodes processing statediffs at head.

**Comment by i-norden** [comment]
We would want to define modulo as well as an offset: `(block_number + offset) % modulo == 0`.

E.g. `(block_number + 0) % 2` and `(block_number + 1) % 2` would define a processing pattern for two clients that alternate every block, providing full coverage.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/go-ethereum/issues/213
