### ISSUE TITLE
(v5) Publish uncle*s* IPLD block `keccak256(rlp(uncles)) => rlp(uncles)`

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#218]
Whereas right now we are treating each uncle as an IPLD (`keccak256(rlp(uncle)) => rlp(uncle))`, using Header multicodec instead of HeaderList multicodec) rather than the entire list of uncles. Relatively minor issue/low priority since uncles are arguably the least interesting object in Ethereum and are not used by any currently conceived watcher... but we should fix this at some point.

**Comment by abdulrabbani00** [comment]
@i-norden - I've spent a bit of time snooping through the codebase, I am still trying to wrap my head around the ask. Do you want us to create a single entry in the `eth.uncle_cids` table for a list of uncles at a given block?

I also see the following line in [several places](https://github.com/vulcanize/go-ethereum/blob/v1.10.18-statediff-v4/statediff/indexer/ipld/eth_header.go#L218) (within the same file):

`commonHashToCid(MEthHeaderList, b.UncleHash)` 

Any insight regarding what we want the end result to be versus what it is would be very helpful. Thank you

**Comment by i-norden** [comment]
@abdulrabbani00 currently when indexing the uncles, we publish and reference each individual header as an IPLD object e.g. https://github.com/vulcanize/go-ethereum/blob/v1.10.18-statediff-v4/statediff/indexer/database/sql/indexer.go#L273 and  https://github.com/vulcanize/go-ethereum/blob/v1.10.18-statediff-v4/statediff/indexer/database/sql/indexer.go#L284 but what we should be doing is publishing the RLP encoded list of uncles (headers) as a single IPLD object. Each separate `uncles_cids` record at a given block would then reference that same uncles IPLD (or we could consider getting rid of the uncle_cids table altogether and embedding that reference in `header_cids` but that's a separate discussion).

**Comment by abdulrabbani00** [comment]
Need an index for the uncles

**Comment by abdulrabbani00** [comment]
PR's:
`ipld-eth-db`: https://github.com/vulcanize/ipld-eth-db/pull/95
`go-ethereum`: https://github.com/vulcanize/go-ethereum/pull/250

**Comment by abdulrabbani00** [comment]
@i-norden - Can you please review the two above PR's
