### ISSUE TITLE
[The Merge] - Implement changes to `eth1` to `geth`, `eth-statediff-service`, and `ipld-eth-db` schema.

### ISSUE THREAD

**Issue by abdulrabbani00** [vulcanize/go-ethereum#220]
All changes to `eth1` data structures must be understood incorporated into our core services. These changes will also more than likely be reflected in the IPLD codecs.

**Comment by i-norden** [comment]
No changes necessary at this time, will reopen or open a new- more specific- issue if changes are required in the future.
