### ISSUE TITLE
Update statediffing file writing mode to write to csv files instead of .sql files

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#224]
Note that the ordering of the columns in the csv need to match the order of the columns in the Postgres tables.

These changes will need to be done in the file writer here: https://github.com/vulcanize/go-ethereum/blob/v1.10.17-statediff-v3.2.0/statediff/indexer/database/file/writer.go

- [x] Implement in go-ethereum
- [x] Implement in eth-statediff-service

**Comment by prathamesh0** [comment]
Reopening to update docs with usage.
