### ISSUE TITLE
Rebase statediffing geth on v1.10.19

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#241]
[1.10.19](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.19) has been released, we need to update our custom geth client to work on top of this release.

This release introduces a hard fork that will be reached by the end of June, so we need to update our stack asap.

We need to perform the rebase only the v4 versions.

- [x] v4 on top of https://github.com/vulcanize/go-ethereum/tree/v1.10.18-statediff-v4 (from that branch, `git checkout -b v1.10.19-statediff-4.0.2-alpha`)

After cutting a release, we will to update the following repos to use these releases:

- [x] eth-statediff-service
- [x] ipld-eth-server
- [ ] migration-tools
- [x] ipld-eth-db-validator
- [x] ipld-eth-state-snapshot
- [x] eth-statediff-fill-service

We will also need to update and release versions of the following repos that use the root v1.10.19 release:

- [x] ipfs-ethdb
- [x] leveldb-ethdb-rpc
- [x] go-eth-state-node-iterator
- [x] eth-ipfs-state-validator

Some changes that necessitate changes in our stack, aside from rebasing our release of this repo and propagating those:
- [ ] We may need to convert away from legacy receipts in our DB before we can run a node again: https://github.com/ethereum/go-ethereum/pull/24943

**Comment by abdulrabbani00** [comment]
* leveldb-ethdb-rpc - https://github.com/vulcanize/leveldb-ethdb-rpc/releases/tag/v0.1.3
* ipfs-ethdb - https://github.com/vulcanize/ipfs-ethdb/releases/tag/v4.0.2-alpha
* go-eth-state-node-iterator- https://github.com/vulcanize/go-eth-state-node-iterator/releases/tag/v1.1.1
* eth-ipfs-state-validator - https://github.com/vulcanize/eth-ipfs-state-validator/releases/tag/v4.0.3-alpha
* eth-statediff-service - https://github.com/vulcanize/eth-statediff-service/releases/tag/v4.0.4-alpha
* gap-filler - https://github.com/vulcanize/gap-filler/releases/tag/v0.4.0
* ipld-eth-server - https://github.com/vulcanize/ipld-eth-server/releases/tag/v4.0.4-alpha
* ipld-eth-db-validator - https://github.com/vulcanize/ipld-eth-db-validator/releases/tag/v4.0.2-alpha
* ipld-eth-state-snapshot - https://github.com/vulcanize/ipld-eth-state-snapshot/releases/tag/v4.1.0-alpha
* eth-statediff-fill-service - https://github.com/vulcanize/eth-statediff-fill-service/releases/tag/v4.0.2-alpha
