### ISSUE TITLE
Modify difference iterator to avoid traversing unnecessary paths when watching addresses

### ISSUE THREAD

**Issue by prathamesh0** [vulcanize/go-ethereum#252]
Use the `descend` flag in difference iterator to skip iterating over paths that are not along the paths to leaf nodes of watched addresses.
See https://github.com/vulcanize/go-ethereum/issues/29#issuecomment-1161690954

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/go-ethereum/issues/252
