### ISSUE TITLE
Generate selector that describes a statediff object as they are produced

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#255]
Look into generating a selector that describes a statediff object as it is being generated. E.g. a selector that describes all the nodes updated in the block, this could be used to quickly recover a statediff object from a full state database (aka IPFS/Filecoin). Shouldn't be too difficult since we are already tracking node paths.

**Comment by i-norden** [comment]
Related, and based on suggestions from Riba while working on Filecoin indexing, we could generate a selector suffix to describe each (leaf node) record in `state_cids` and `storage_cids`. This suffix could be appended to a root hash to generate a selector which describes how to select all the nodes required to prove the leaf node.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/go-ethereum/issues/255
