### ISSUE TITLE
Can we use the concurrent node iterator when statediffing at head?

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#286]
We may need to use a different StaetDB than the one that the node's core `trie.TrieDB` uses, meaning it will not be able to share a fastcache.

**Comment by roysc** [comment]
I think this can be done without any major complications, and we should even be able to use the same node cache.
The `trie.Database` is thread-safe for reads:
```
// Note, the trie Database is **not** thread safe in its mutations, but it **is**
// thread safe in providing individual, independent node access. The rationale
// behind this split design is to provide read access to RPC handlers and sync
// servers even while the trie is executing expensive garbage collection.
```
And `state.Database` is as well. `Trie` instances are not, but caching is performed at the TrieDB level.

Also, implementing this should bring the performance up to par with `ipld-eth-state-snapshot`, and then I believe we could strip that code down to a service that just calls into this.

**Comment by i-norden** [comment]
Awesome! Implemented by @roysc here: https://git.vdb.to/cerc-io/plugeth-statediff/pulls/12
