### ISSUE TITLE
Rebase stack to v1.10.26

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#287]
[1.10.26](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.26) has been released, we need to update our custom geth client to work on top of this release.

We need to perform the rebase only the v4 version of things

- [x] https://github.com/cerc-io/go-ethereum

After cutting a release, we will to update the following repos to use this release:

- [x] eth-statediff-service
- [x] ipld-eth-server
- [x] ipld-eth-db-validator
- [x] ipld-eth-state-snapshot
- [x] eth-statediff-fill-service

We will also need to update and release versions of the following repos that use the root v1.10.26 release:

- [x] ipfs-ethdb
- [x] leveldb-ethdb-rpc
- [x] go-eth-state-node-iterator
- [x] eth-ipfs-state-validator

NOTE:
* Update these first, as multiple others depend on them: ipfs-ethdb, go-eth-state-node-iterator.
* ipld-eth-db-validator depends on ipld-eth-server, so ipld-eth-server needs to be updated prior.
* There don't appear to be any functional or API changes in the release that need to be accounted for.
* I may have missed some of the dependent repos.

**Comment by ABastionOfSanity** [comment]
https://github.com/cerc-io/go-ethereum/releases/tag/v1.10.26-statediff-4.2.2-alpha
published by:
https://github.com/cerc-io/go-ethereum/actions/runs/3396649335

**Comment by ABastionOfSanity** [comment]
Dependency graph:
https://www.notion.so/Geth-Related-Dependency-Graph-c5a57eca898a4d9e9f692fe17ab93279

**Comment by ABastionOfSanity** [comment]
Also updated:
https://github.com/vulcanize/gap-filler
