### ISSUE TITLE
Statediff lock contention in database 

### ISSUE THREAD

**Issue by dboreham** [vulcanize/go-ethereum#293]
Many concurrent transactions blocked on locks held by transactions that executed statements like this then appear to have stalled idle waiting on the next statement:

```
INSERT INTO eth.header_cids (block_number, block_hash, parent_hash, cid, td, node_id, reward, state_root, tx_root, receipt_root, uncle_root, bloom, timestamp, mh_key, times_validated, coinbase)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
			ON CONFLICT (block_hash, block_number) DO UPDATE SET (parent_hash, cid, td, node_id, reward, state_root, tx_root, receipt_root, uncle_root, bloom, timestamp, mh_key, times_validated, coinbase) = ($3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, eth.header_cids.times_validated + 1, $16)
```

From this code? https://github.com/cerc-io/go-ethereum/blob/v1.10.25-statediff-v4/statediff/indexer/database/sql/writer.go#L48

**Comment by dboreham** [comment]
Possibly something to do with here where the txn is opened then lazily committed: 

https://github.com/cerc-io/go-ethereum/blob/v1.10.25-statediff-v4/statediff/indexer/database/sql/indexer.go#L90

**Comment by i-norden** [comment]
It seems there are two issues at play. The first being that a contention is occurring on header_cids in the first place (e.g. why are we seeing the same `(block_number, block_hash)` tuple); and the second being that when this occurs the lock never resolves because the blocking tx appears to hang.

Optimizing the tx lifecycle *might* address the later problem, but we still haven’t identified where the former is coming from.

Have a patch idea in mind for the tx lifecycle. Testing is going to be complicated since we’re only seeing this issue somewhat sparsely under our current mainnet deployment conditions.

Pinging @roysc as he might have some insight and can possible help with the patch.

**Comment by dboreham** [comment]
Would it be useful to have logging of the DB queries executed along with some general "here's what I'm doing" log output? Then we could potentially reconstruct the scenario that leads to contended inserts by analysis of the log output.

**Comment by i-norden** [comment]
Yeah that would be helpful, we should be abel to get the "here's what I'm doing" output by changing the log level to "info" or perhaps "debug"(if we want even more detail) for the geth node.

**Comment by i-norden** [comment]
It should also be noted that this issue is not presenting itself in the statediffing service on Kraven

**Comment by i-norden** [comment]
Nothing that @srwadleigh also mentioned optimizations to the Kraven postgres server that may not have been made to Carrion

**Comment by telackey** [comment]
https://github.com/cerc-io/ipld-eth-server/issues/209 appears to be related.  I was able to cause it simply by looping a set of operations, executed sequentially.  I suspect the eth_getStorageAt ones to be the culprit, but that's not been confirmed.

The result was lots of messages like this on the geth side:

```
INFO [12-22|20:28:13.681] writing state diff for                   block hash=d9ee39..21fdb6
WARN [12-22|20:28:13.697] Served statediff_writeStateDiffFor       conn=172.29.0.5:60674 reqid=9949 duration=15.90455ms   err="pq: sorry, too many clients already"
INFO [12-22|20:28:14.032] writing state diff for                   block hash=d9ee39..21fdb6
WARN [12-22|20:28:14.045] Served statediff_writeStateDiffFor       conn=172.29.0.5:60674 reqid=9951 duration=12.418582ms  err="pq: sorry, too many clients already"
INFO [12-22|20:28:14.259] writing state diff for                   block hash=d9ee39..21fdb6
WARN [12-22|20:28:14.271] Served statediff_writeStateDiffFor       conn=172.29.0.5:60674 reqid=9953 duration=12.255946ms  err="pq: sorry, too many clients already"
INFO [12-22|20:28:17.144] writing state diff for                   block hash=d9ee39..21fdb6
INFO [12-22|20:28:17.394] writing state diff for                   block hash=d9ee39..21fdb6
```

In the DB, I saw >75 transactions waiting on locks, all of the form:

```
INSERT INTO eth.header_cids (block_number, block_hash, parent_hash, cid, td, node_id, reward, state_root, tx_root, receipt_root, uncle_root, bloom, timestamp, mh_key, times_validated, coinbase) VALUES ($1,     $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) ON CONFLICT (block_hash, block_number) DO UPDATE SET (parent_hash, cid, td, node_id, reward, state_root, tx_root, receipt_root, uncle_root,     bloom, timestamp, mh_key, times_validated, coinbase) = ($3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, eth.header_cids.times_validated + 1, $16)
```

**Comment by i-norden** [comment]
@dboreham @telackey with all the fixes/improvements that have been made since opening this, can we close this?

**Comment by dboreham** [comment]
Yes, it turned out to be due to the watcher triggering state diffing at head concurrently with block production.
