### ISSUE TITLE
Make logging level configurable during runtime

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#302]
From talking with @srwadleigh 

This would help with debugging issues which pop up during operation without requiring us to bring down the node and bring it up with a different log level. Even more valuable in situations where an issue only occurs under mainnet/production conditions after some accumulation of time/events, as in this case when we cycle the node to investigate the issue the issue may have dissolved during the process of cycling the node.

**Comment by telackey** [comment]
I think you can use the `debug` API to do this, specifically the `debug_verbosity` and `debug_vmodule` methods:

https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugverbosity
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugvmodule

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/go-ethereum/issues/302
