### ISSUE TITLE
go-ethereum 1.11.2 rebase

### ISSUE THREAD

**Issue by ABastionOfSanity** [vulcanize/go-ethereum#318]
Rebase onto latest 1.11.2 release

**Comment by i-norden** [comment]
Some of the previous rebase issues have some decent templates to use for this one: https://github.com/cerc-io/go-ethereum/issues/287

**Comment by i-norden** [comment]
I will handle the v5 rebase once things are no longer in flux

**Comment by i-norden** [comment]
We aren't rebasing on 1.11.1

**Comment by i-norden** [comment]
Do we have any idea when this will be done? There have already been two more releases since 1.11.2

**Comment by i-norden** [comment]
If this issue is only tracking the rebase of this repo, please close it, but I don't see an issue that tracks the progress of all associated repos.

**Comment by i-norden** [comment]
This wasn't finished before https://github.com/cerc-io/go-ethereum/issues/344 was started, so now we have a weird intermediate state where more than half our repos have a 1.11.2 rebase and some also have a 1.11.4 rebase. I don't think it is worth going back and finishing the 1.11.2, but we <s>should</s> need to finish the 1.11.4.
