### ISSUE TITLE
Run all tests in Jenkins

### ISSUE THREAD

**Issue by ABastionOfSanity** [vulcanize/go-ethereum#331]
# Rationale

Why should this feature exist?
-Github action runner is producing inconsistent unit test failures.

What are the use-cases?
-Automated unit tests to eliminate inconsistencies in other environs.

# Implementation

Do you have ideas regarding the implementation of this feature?
https://github.com/cerc-io/go-ethereum/tree/unit_test_inconsistencies

**Comment by ABastionOfSanity** [comment]
baseline geth unit tests implemented... 
statediffing tests much more complicated, as they require multiple containers (db and migrations) 
and the jenkins host is not configured to run
**_make statedifftest_**
currently.

**Comment by i-norden** [comment]
As I understand it we will use ACT instead of Jenkins, please re-open if I am mistaken
