### ISSUE TITLE
Provide documentation for the concurrent iterator package

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#335]
We never wrote proper documentation when it was a standalone library, now that we have [internalized it ](https://github.com/cerc-io/go-ethereum/tree/v1.11.2-statediff-v4/trie/concurrent_iterator)we should still provide some simple documentation. Low priority, good filler task.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/go-ethereum/issues/335
