### ISSUE TITLE
Async `WriteStateDiffFor` 

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#356]
In https://github.com/cerc-io/go-ethereum/pull/306 `WriteStateDiffAt` was made async and now returns a `JobID` whose progress can be monitored with the `StreamWrites` endpoint now, but `WriteStateDiffFor` is still using the old sync pattern. This should be a quick patch and done at the same time as #355 

Included in this issue, we need to add test coverage for the changes in https://github.com/cerc-io/go-ethereum/pull/306 and the new changes here.

**Comment by i-norden** [comment]
It seems the async method + streamWrites is broken, see CICD history on this PR: https://github.com/cerc-io/eth-statediff-fill-service/pull/16

Can get tests to pass by using the sync `WriteStateDiffFor` method, but not with async `WriteStateDiffAt` using `StreamWrites` to wait for completion.

I may also have made a mistake on the subscriber side.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/go-ethereum/issues/356
