### ISSUE TITLE
Link to existing README

### ISSUE THREAD

**Issue by zramsay** [vulcanize/go-ethereum#362]

**Comment by i-norden** [comment]
https://github.com/cerc-io/go-ethereum/blob/v1.11.5-statediff-v4/statediff/README.md needs to be updated for [v5](https://github.com/cerc-io/go-ethereum/tree/v1.11.5-statediff-v5/statediff) but otherwise is good, no?

**Comment by i-norden** [comment]
Needs better visibility though, perhaps we make this the first section of the top-level readme?

**Comment by i-norden** [comment]
Even the v4 one is a bit outdated

**Comment by i-norden** [comment]
Where does this link go?
