### ISSUE TITLE
Support EIP-2930

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#64]
Firstly just assert we can index EIP-2930 txs as normal, without the additional fields/rows and with no issues in storing them as IPLDs.

Secondly, adjust the code and database schemas to decode and index the new access list.

**Comment by i-norden** [comment]
We are running into error like this until we support it: `statediff.Service.WriteLoop: processing error block height=12323727 error="error creating IPLD nodes from block and receipts: wrong transaction hash computed" worker=8`

This is because for 2930 txs it is not just the RLP encoded tx that is stored in the trie, but rather `0x01 || RLP(tx)` so the `EncodeRLP()` method does not work any more and we need to use `MarshalBinary()`.

The same is true for receipts, except we need to add the `MarshalBinary()` method first.

**Comment by i-norden** [comment]
Addressed in #68

**Comment by AFDudley** [comment]
https://vulcanize.slack.com/archives/CGY8XDDNZ/p1620102149463900

**Comment by i-norden** [comment]
I think we can close this now?
