### ISSUE TITLE
Replace DB migrations

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#73]
* `make` targets that build Postgres instance and run the full incremental set of migrations from [statediff-migrations](https://github.com/vulcanize/statediff-migrations)
* Remove the "concise" set of migrations and db schema from this repo and put it in https://github.com/vulcanize/ipld-eth-db
* Create documentation for the db schema/tables
* Same [here](https://github.com/vulcanize/ipld-eth-server/issues/61)

**Comment by arijitAD** [comment]
`address` column in `log_cids` table should be `NOT NULL`
https://github.com/vulcanize/statediff-migrations/pull/7#pullrequestreview-740905189
Currently, in [geth statediff](https://github.com/vulcanize/go-ethereum/blob/55d2466745fb17b2db9bdca75adb3477fe4989ea/statediff/db/migrations/00016_create_eth_log_cids_table.sql#L7) the column can have `NULL` values.
