### ISSUE TITLE
Familiarize with go-ethereum release schedule and our rebase approach

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#74]

**Comment by i-norden** [comment]
Blocked by me doing: https://github.com/vulcanize/go-ethereum/issues/70

**Comment by arijitAD** [comment]
This [doc](https://github.com/vulcanize/go-ethereum/pull/75/files) helped me understand the release process.
I am planning to make the next release. I will closed this issue once that is done.

**Comment by arijitAD** [comment]
Working on new release https://github.com/ethereum/go-ethereum/releases/tag/v1.10.4

**Comment by arijitAD** [comment]
Made a new release https://github.com/vulcanize/go-ethereum/pull/93 Closing this.
