### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/go-ethereum#78]
* Integrate running unit tests on PR/merge

**Comment by arijitAD** [comment]
Currently, we have two CI trigger on a pull request.
1. [Github action](https://github.com/vulcanize/go-ethereum/blob/v1.10.3-statediff-0.0.22/.github/workflows/on-pr.yml) which builds [this docker file](https://github.com/vulcanize/go-ethereum/blob/master/Dockerfile).
2.  [Travis](https://github.com/vulcanize/go-ethereum/blob/master/.travis.yml) which comes from upstream and runs test related to `geth`.

The proposal is to let both the CI co-exist and trigger on each PR
1. Github action will be responsible for building and running `statediff` unit tests for the vulcanize eth.
2. Travis will run `geth` unit test which will allow us to verify that  `geth` is not broken after intergration with `statediff`

**Comment by arijitAD** [comment]
https://github.com/vulcanize/go-ethereum/pull/83
Integrated the unit test in Github action and fixed a couple of tests in Travis. Currently, Travis CI is timing out.

**Comment by arijitAD** [comment]
The Tests are added in CI. https://github.com/vulcanize/go-ethereum/pull/83
