### ISSUE TITLE
EIP1559 support for IPLD indexing

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#80]
EIP 1559 has been merged into root master (but hasn't made it into a release yet).  We need to add support for the new `BaseFee` field in the header and new [tx type](https://github.com/ethereum/go-ethereum/blob/92b8f28df3255c6cef9605063850d77b46146763/core/types/dynamic_fee_tx.go#L25) before the London hard fork.

The tx updates will be very similar to those in these commits to support 2930 tx type: [indexing updates](https://github.com/vulcanize/go-ethereum/pull/68/commits/d91faa8ba32ca0ff8e4e877d0f699e20dde011dd), [db model updates](https://github.com/vulcanize/go-ethereum/pull/68/commits/51659c28a674a49e55cc387800083766031fe530), [metrics updates](https://github.com/vulcanize/go-ethereum/pull/68/commits/abbb7b77ff6f919e67fd604ae779a26ea7875416), [unit tests](https://github.com/vulcanize/go-ethereum/pull/68/commits/971f7fa8be29cf54bc4e34f75f14c1ddb61a1c35).

**Comment by arijitAD** [comment]
Issue is fixed in this PR https://github.com/vulcanize/go-ethereum/pull/93
