### ISSUE TITLE
Release docker image of dapptools with every release of this repo.

### ISSUE THREAD

**Issue by arijitAD** [vulcanize/go-ethereum#82]
The latest docker image of [dapptools](https://hub.docker.com/layers/vulcanize/dapptools/v0.29.0-v1.10.2-statediff-0.0.19/images/sha256-8dbf4c5f2e48c43731a403d166e4ac985b64e536c611c5524451736a9b51af24?context=explore) is pointing to statediff v0.0.19 while the latest release is [v0.0.22](https://github.com/vulcanize/go-ethereum/tree/v1.10.3-statediff-0.0.22)
Link: https://github.com/vulcanize/dapptools

**Comment by i-norden** [comment]
This is deprecated by @abdulrabbani00's work on Foundry and Hive.
