### ISSUE TITLE
We need to build portable, monolithic binaries that are compatible with CentOS

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/go-ethereum#88]
Problem:
The GitHub Actions are building binaries for Ubuntu, and when you run it on CentOS it cannot find certain files. This impacts being able to implement a continuous deployment process.

Solution:
We need to move towards a monolithic, portable binary that has no shared library dependencies.

**Comment by arijitAD** [comment]
Build static Linux binaries for and publish in assets.

**Comment by i-norden** [comment]
@ABastionOfSanity @srwadleigh @dboreham not sure how this fits into the CI/CD work you are doing but going to close this as it is very old and the problem it was opened to address doesn't really exist in it's described form anymore.

**Comment by dboreham** [comment]
Ok I guess we'll learn if this is still an issue. Upstream geth seems to ship a unified binary for all Linux fwiw.
