### ISSUE TITLE
Relax our dependency on LevelDB and move towards stateless design

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/go-ethereum#89]
We need to relax our dependency on go-ethereum's LevelDB and move towards a more stateless design. This will allow us to containerize Vulcanize Geth in addition to move towards client diversity.

How we will accomplish this:
- Pre-warm up state from Geth:
    - we need to trick Geth into thinking it has passed the "pivot point"
    - code loads from postgres up to the pivot point, instead of relying on LevelDB, then starts geth after the pivot point
- Re-write the code so it doesn't persist any state to LevelDB

**Comment by i-norden** [comment]
This is superseded by https://github.com/vulcanize/issue_tracking/issues/4
